### ISSUE TITLE
Building instructions 

### ISSUE THREAD

**Issue by slashbeast** [sommd/auto-mute#11]
Hi,

I am looking to build this locally as I cannot find a prebuilt one and it is not on homebrew (another app under the same name is present). I am unable to build it because of

```
/Users/piotr/src/automute/automute.xcodeproj No profiles for 'com.yonilevy.mutejack' were found: Xcode couldn't find any Mac App Development provisioning profiles matching 'com.yonilevy.mutejack'.
```

Would you be able to provide some additional build instructions for this?

**Comment by sommd** [comment]
Uhh, this is an Android app 😅. Sounds like you want a macOS app, and this project isn't that.

If you do want to build the Android app you'll need to use Android Studio, and building it works like any other Android app using Android Studio.

**Comment by slashbeast** [comment]
> Uhh, this is an Android app 😅. Sounds like you want a macOS app, and this project isn't that.
> 
> If you do want to build the Android app you'll need to use Android Studio, and building it works like any other Android app using Android Studio.

Oh wow, I was sure I am in https://github.com/yonilevy/automute repo. Sorry about the noise and thanks for pointing it out!
