### ISSUE TITLE
Missing Update in Google PlayStore

### ISSUE THREAD

**Issue by JanWaldhorn** [sommd/auto-mute#6]
Thanks for the great app. The app in Playstore is still at [V1.4.0 from February 2022](https://play.google.com/store/apps/details?id=xyz.sommd.automute), while on [GitHub V1.5. is available since September.](https://github.com/sommd/auto-mute/releases/tag/v1.5.0)

**Comment by sommd** [comment]
Woops, had the release uploaded to Google Play and everything and I just forgot to actually hit release :sweat_smile:. Should be up now.
